cd ..
sam Hello my name is SAM.
sam I will sing the national anthem of the united states of America.
sam The star spangled banner!
sam -sing -speed 40 -pitch 64 -phonetic ohohoh
sam -sing -speed 40 -pitch 76 -phonetic ohohoh
sam -sing -speed 40 -pitch 96 -phonetic sehehehehehehehehehey
sam -sing -speed 40 -pitch 76 -phonetic kaeaeaeaeaeaeaeaeaen
sam -sing -speed 40 -pitch 64 -phonetic yuxuxuxuxuxuxw
sam -sing -speed 40 -pitch 48 -phonetic siyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 38 -phonetic baaaaay
sam -sing -speed 40 -pitch 42 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 48 -phonetic daoaoaoaoaoaoaonz
sam -sing -speed 40 -pitch 76 -phonetic ererererererer
sam -sing -speed 40 -pitch 68 -phonetic liyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 64 -phonetic laaaaaaaaaaaaaaaaaaaaaaaaayt
sam -sing -speed 40 -pitch 64 -phonetic whahahaht
sam -sing -speed 40 -pitch 64 -phonetic sohohuw
sam -sing -speed 40 -pitch 38 -phonetic praaaaaaaaaaaaaaaauwd
sam -sing -speed 40 -pitch 42 -phonetic liyiyiy
sam -sing -speed 40 -pitch 48 -phonetic wiyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 51 -phonetic /heheheheheheheheheheheheheheheheheheyld
sam -sing -speed 40 -pitch 56 -phonetic aeaeaeaet
sam -sing -speed 40 -pitch 51 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 48 -phonetic twaaaaaaaaaaaaaaiy
sam -sing -speed 40 -pitch 48 -phonetic laaaaaaaaaaaaiyts
sam -sing -speed 40 -pitch 64 -phonetic laeaeaeaeaeaeaeaeaest
sam -sing -speed 40 -pitch 76 -phonetic gliyiyiyiyiyiyiyiyiym
sam -sing -speed 40 -pitch 96 -phonetic mihihihihihihihihihihnx
sam -sing -speed 40 -pitch 64 -phonetic /huxuxuxuxuxuxuxuxuxuxwz
sam -sing -speed 40 -pitch 76 -phonetic braoaoaod
sam -sing -speed 40 -pitch 96 -phonetic straaaaaaaaaaaaiyps
sam -sing -speed 40 -pitch 76 -phonetic aeaeaeaeaeaeaeaeaeaend
sam -sing -speed 40 -pitch 64 -phonetic braaaaaaaaaaaaaaiyt
sam -sing -speed 40 -pitch 48 -phonetic staaaaaaaaaaaaaaaaaaaaaaaaaarz
sam -sing -speed 40 -pitch 38 -phonetic thruxuxw
sam -sing -speed 40 -pitch 42 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 48 -phonetic pehehehehehehehehehehr
sam -sing -speed 40 -pitch 76 -phonetic rixixixixixixixixixixixixl
sam -sing -speed 40 -pitch 68 -phonetic lahahahahahahahahahs
sam -sing -speed 40 -pitch 64 -phonetic faaaaaaaaaaaaaaaaaaaaaaaaaaiyt
sam -sing -speed 40 -pitch 64 -phonetic ohohohr
sam -sing -speed 40 -pitch 64 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 38 -phonetic raeaeaeaeaeaeaeaeaeaeaeaem
sam -sing -speed 40 -pitch 42 -phonetic paaaarts
sam -sing -speed 40 -pitch 48 -phonetic wiyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 51 -phonetic waaaaaaaaaaaaaaaaaaaaaaaaaachd
sam -sing -speed 40 -pitch 56 -phonetic werer
sam -sing -speed 40 -pitch 51 -phonetic sohohw
sam -sing -speed 40 -pitch 48 -phonetic gaeaeaeaeaeaeaeaeaeael
sam -sing -speed 40 -pitch 48 -phonetic lixixixixixixixixixixixixixnt
sam -sing -speed 40 -pitch 64 -phonetic liyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 76 -phonetic striyiyiyiyiyiyiyiyiym
sam -sing -speed 40 -pitch 96 -phonetic mihihihihihihihihihnx
sam -sing -speed 40 -pitch 38 -phonetic aeaeaeaeaend
sam -sing -speed 40 -pitch 38 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 38 -phonetic raaaaaaaaaaaak
sam -sing -speed 40 -pitch 36 -phonetic kixixixixixixixixixixixts
sam -sing -speed 40 -pitch 32 -phonetic rehehehehehehehehehd
sam -sing -speed 40 -pitch 32 -phonetic gleheheheheheheheheheheheheheheherer
sam -sing -speed 40 -pitch 36 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 38 -phonetic baaaamz
sam -sing -speed 40 -pitch 42 -phonetic bererererererst
sam -sing -speed 40 -pitch 38 -phonetic tihihihihihihihihihnx
sam -sing -speed 40 -pitch 36 -phonetic ihihihihihihihihihihn
sam -sing -speed 40 -pitch 36 -phonetic eheheheheheheheheheheheheheheheheheyr
sam -sing -speed 40 -pitch 36 -phonetic geheheheyv
sam -sing -speed 40 -pitch 38 -phonetic pruxuxuxuxuxuxuxuxuxuxuxuxwf
sam -sing -speed 40 -pitch 42 -phonetic thruxuxw
sam -sing -speed 40 -pitch 48 -phonetic dhaaaxaxax
sam -sing -speed 40 -pitch 51 -phonetic naaaaaaaaaaaaaaaaaaaaaaayiyt
sam -sing -speed 40 -pitch 56 -phonetic dhaeaeaeaet
sam -sing -speed 40 -pitch 51 -phonetic aaaaaauwr
sam -sing -speed 40 -pitch 48 -phonetic flaeaeaeaeaeaeaeaeaeg
sam -sing -speed 40 -pitch 76 -phonetic wahahahahahahahahahz
sam -sing -speed 40 -pitch 68 -phonetic stihihihihihihihihihl
sam -sing -speed 40 -pitch 64 -phonetic dhehehehehehehehehehehehehehehehehehehehr
sam -sing -speed 40 -pitch 64 -phonetic ohohohohohohow
sam -sing -speed 40 -pitch 48 -phonetic sehehehehehehehehehey
sam -sing -speed 40 -pitch 48 -phonetic dahahahahahahahahahz
sam -sing -speed 40 -pitch 48 -phonetic dhaeaeae
sam -sing -speed 40 -pitch 51 -phonetic aeaeaet
sam -sing -speed 40 -pitch 56 -phonetic staaaaaaaaaaaar
sam -sing -speed 40 -pitch 56 -phonetic spehehehehehehehehehiynx
sam -sing -speed 40 -pitch 56 -phonetic gaxaxaxaxaxaxaxaxaxaxaxaxld
sam -sing -speed 40 -pitch 42 -phonetic baeaeaeaeaeaeaeaeaen
sam -sing -speed 40 -pitch 36 -phonetic nerer
sam -sing -speed 40 -pitch 38 -phonetic ererer
sam -sing -speed 40 -pitch 42 -phonetic yeheheh
sam -sing -speed 40 -pitch 48 -phonetic eheheheht
sam -sing -speed 40 -pitch 48 -phonetic weheheheheheheheheheheh
sam -sing -speed 40 -pitch 51 -phonetic ehehehehehehehiyiyiyv
sam -sing -speed 40 -pitch 64 -phonetic ohohohr
sam -sing -speed 40 -pitch 64 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 48 -phonetic laeaeaeaeaeaeaeaeaeaeaeae
sam -sing -speed 40 -pitch 42 -phonetic aeaeaend
sam -sing -speed 40 -pitch 38 -phonetic ahahahv
sam -sing -speed 40 -pitch 36 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 32 -phonetic friyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiyiy
sam -sing -speed 40 -pitch 48 -phonetic aeaeaend
sam -sing -speed 40 -pitch 42 -phonetic dhaaaxaxaxax
sam -sing -speed 40 -pitch 38 -phonetic /hohohohohohohohohowm
sam -sing -speed 40 -pitch 36 -phonetic ahahahahv
sam -sing -speed 40 -pitch 42 -phonetic dhaaaxaxaxaxaxaxaxaxaxaxaxaxax
sam -sing -speed 40 -pitch 48 -phonetic brehehehehehehehehehehiyiyiyv
